import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./components/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RedditRevs",
  description: "Generated by RedditRevs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
<meta name="google-site-verification" content="pmJDDuzG82F_LCdbkb9IDHTtdk4fGN5Pvi3z69GIdwY" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-[#FF5F1F]`}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
