import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Provider from "@/app/components/provider";
import Navbar from "@/app/components/NavbarComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-y-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white overflow-y-hidden h-screen`}
      >
        <Provider>
          <Navbar />
          <main className="overflow-y-hidden h-full">
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
